openshift:
  routes:
    proxy:
      enabled: true
      tls:
        enabled: true
        termination: passthrough
    manager:
      enabled: false
      tls:
        enabled: true
        termination: passthrough
    admin:
      enabled: false
      tls:
        enabled: true
        termination: passthrough
    portal:
      enabled: false
      tls:
        enabled: true
        termination: passthrough
    portalapi:
      enabled: false
      tls:
        enabled: true
        termination: passthrough
    clustertelemetry:
      enabled: false
    cluster:
      enabled: false
